import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/componants/navbar/Navbar";
import Fotter from "@/componants/fotter/Fotter";
import { TimelineProvider } from "@/context/TimelineContext";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { Poppins } from "next/font/google";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={` ${poppins.className} ${geistSans.variable} ${geistMono} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-[#F7F6F3]">
        <Navbar />

        <TimelineProvider>{children}</TimelineProvider>
        <ToastContainer
          position="top-right"
          autoClose={2000}
          hideProgressBar={false}
          closeOnClick
          pauseOnHover
          draggable
          theme="dark"
        />

        <Fotter />
      </body>
    </html>
  );
}
